### ISSUE TITLE
Add option to ask for confirmation when button get's pressed

### ISSUE THREAD

**Issue by keyflight** [sublayerio/ui#40]
```yaml
type: button
settings:
  confirmation: true
```

with custom confirmation message
```yaml
type: button
settings:
  confirmation: Do you want to execute this action?
```
